// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq8zwr6EVYIRQs1LEkdJ9eygW-koB0sDA',
    appId: '1:180734955649:web:cf98fa1a7c5950c31ebd80',
    messagingSenderId: '180734955649',
    projectId: 'auth-task-7026d',
    authDomain: 'auth-task-7026d.firebaseapp.com',
    storageBucket: 'auth-task-7026d.firebasestorage.app',
    measurementId: 'G-GLGXLDL1TG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKWe0mBaOHTDZtY7ur7eA3nkgOZpQTYEQ',
    appId: '1:180734955649:android:241e73f32fd9069a1ebd80',
    messagingSenderId: '180734955649',
    projectId: 'auth-task-7026d',
    storageBucket: 'auth-task-7026d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVXRHyPKECr0obPuZq4QC1rmGUYqSOE3Y',
    appId: '1:180734955649:ios:e190e4b532ae086c1ebd80',
    messagingSenderId: '180734955649',
    projectId: 'auth-task-7026d',
    storageBucket: 'auth-task-7026d.firebasestorage.app',
    iosBundleId: 'com.example.authenticationTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVXRHyPKECr0obPuZq4QC1rmGUYqSOE3Y',
    appId: '1:180734955649:ios:e190e4b532ae086c1ebd80',
    messagingSenderId: '180734955649',
    projectId: 'auth-task-7026d',
    storageBucket: 'auth-task-7026d.firebasestorage.app',
    iosBundleId: 'com.example.authenticationTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq8zwr6EVYIRQs1LEkdJ9eygW-koB0sDA',
    appId: '1:180734955649:web:1a84d790af32e1af1ebd80',
    messagingSenderId: '180734955649',
    projectId: 'auth-task-7026d',
    authDomain: 'auth-task-7026d.firebaseapp.com',
    storageBucket: 'auth-task-7026d.firebasestorage.app',
    measurementId: 'G-YG60STDYQL',
  );
}
